TravelMate/urls.py
from django.conf.urls import include,url
from django.contrib import admin

urlpatterns = [
    # first landing page - /
    url(r'^', include('travel.urls')),
    #admin url - /admin
    url(r'^admin/', admin.site.urls),
    #book url - /book
    url(r'^book/', include('book.urls')),
    #offer url - /offer
    url(r'^offer/', include('offer.urls')),
    #myride url - /myride
    url(r'^myride/', include('myride.urls')),
]

book/urls.py
from django.conf.urls import url
from . import views

app_name = 'book'

urlpatterns = [
    #/book/<userid>/
    url(r'^(?P<userid>[0-9]+)/$', views.index, name = 'index'),
    #/book/<userid>/search
    url(r'^(?P<userid>[0-9]+)/search/', views.searchres, name = 'searchres'),
    #/book/<userid>/bookdetails
    url(r'^(?P<userid>[0-9]+)/bookdetails/', views.bookdetails, name = 'bookdetails'),
]

offer/urls.py
from django.conf.urls import url
from . import views

app_name = 'offer'

urlpatterns = [
    #/offer/<userid>/
    url(r'^(?P<userid>[0-9]+)/$', views.index, name = 'index'),
    #/offer/<userid>/offerdetails
    url(r'^(?P<userid>[0-9]+)/offerdetails/', views.offerdetails, name = 'offerdetails'),
    #/offer/<userid>/delete
    url(r'^(?P<userid>[0-9]+)/delete/', views.deleteride, name = 'deleteride'),
    #/offer/<userid>/offerings
    url(r'^(?P<userid>[0-9]+)/offerings/', views.allofferedrides, name = 'allofferedrides'),
]

travel/urls.py
from django.conf.urls import url
from . import views

app_name = 'travel'

urlpatterns = [
    #/
    url(r'^$', views.index, name = 'index'),
    #/login
    url(r'^login/', views.login, name = 'login'),
    #/login
    url(r'^loginsubmit/', views.loginsubmit, name = 'loginsubmit'),
    #/register
    url(r'^register/', views.register, name = 'register'),
    #/registersubmit
    url(r'^registersubmit/', views.registersubmit, name = 'registersubmit'),
    #/signout
    url(r'^signout/', views.logout_view, name = 'signout'),
]

travel/models.py
from __future__ import unicode_literals

from django.db import models

# Create your models here.

class User(models.Model):
    fname = models.CharField(max_length = 250)
    lname = models.CharField(max_length = 250)
    phone = models.IntegerField()
    email = models.CharField(max_length = 250)
    rating = models.FloatField(default=5.0)


    def __str__(self):
        return self.fname + '-' + self.lname

travel/views.py
from django.shortcuts import render,get_object_or_404
from .models import User as GenUser
from django.contrib.auth.models import User
from django.contrib.auth import authenticate,logout
from django.contrib.auth import login as auth_login


def index(request):
    return render(request,'travel/index.html')

def login(request):
    return render(request,'travel/login.html')

def loginsubmit(request):
    mailid = request.POST.get('mail')
    username = mailid.split('@',1)[0]
    password = request.POST.get('password')
    user = authenticate(username = username, password = password)
    if user is not None:
        if user.is_active:
            auth_login(request, user)
            loggeduser = get_object_or_404(GenUser,email = mailid)
            request.session['userid'] = loggeduser.id
            request.session['username'] = user.username
            return render(request,'travel/index.html')
    context = {'error':"Enter Valid Credentials"}
    return render(request,'travel/login.html',context)

def register(request):
    return render(request,'travel/register.html')

def registersubmit(request):
    genuser = GenUser()
    genuser.fname = request.POST.get('fname')
    genuser.lname = request.POST.get('lname')
    genuser.phone = request.POST.get('number')
    genuser.email = request.POST.get('mail')
    mailid = request.POST.get('mail')
    user = User()
    user.username = mailid.split('@',1)[0]
    password = request.POST.get('password')
    user.set_password(password)
    user.save()
    genuser.save()
    loggeduser = get_object_or_404(GenUser,email = mailid)
    request.session['userid'] = loggeduser.id
    request.session['username'] = user.username
    return render(request,'travel/index.html')


def logout_view(request):
    if request.session.has_key('username'):
        del request.session['username']
    if request.session.has_key('userid'):
        del request.session['userid']
    logout(request)
    return render(request,'travel/index.html')

travel/templates/travel/index.html
<!--<h1>Hello Index page</h1>
<a href ='/book'> Book a ride </a> <br>
<a href ='/offer'> Offer a ride </a><br>
<a href ='/myride'> My Rides </a>-->

{%load staticfiles %}
<!--Bootstrap -->
<link rel="stylesheet" href="{%static 'css/bootstrap.min.css'%}" type="text/css">
<!--Custome Style -->
<link rel="stylesheet" href="{%static 'css/style.css'%}" type="text/css">
<!--OWL Carousel slider-->
<link rel="stylesheet" href="{%static 'css/owl.carousel.css'%}" type="text/css">
<!--FontAwesome Font Style -->
<link href="{%static 'css/font-awesome.min.css'%}" rel="stylesheet">

<!-- Google-Font-->
<link href="https://fonts.googleapis.com/css?family=Montserrat:300,400,500,700,800" rel="stylesheet">
<link href="https://fonts.googleapis.com/css?family=Open+Sans:300,400,600,700" rel="stylesheet">
<header id="header">
  <nav class="navbar navbar-default navbar-fixed-top" data-spy="affix" data-offset-top="10">
    <div class="container">
      <div class="navbar-header">
        <div class="logo"> <a href="{% url 'travel:index' %}"><img src="{%static 'images/logo1.png'%}" alt="image"/></a> </div>
        <button id="menu_slide" data-target="#navigation" aria-expanded="false" data-toggle="collapse" class="navbar-toggle collapsed" type="button">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
      </div>
      <div class="collapse navbar-collapse" id="navigation">
        <ul class="nav navbar-nav">
          {% if request.session.username%}
          <li ><a href="#">{{request.session.username}}</a> <span class="arrow"></span>
            <ul class="sub-menu">
              <li><a href="/myride">My Rides</a></li>
              <li><a href="{% url 'offer:allofferedrides' request.session.userid %}">My Offerings</a></li>
              <!--<li><a href="#">My Profile</a></li>-->
            </ul>
          </li>
          <li><a href="{% url 'travel:signout'%}">Sign Out</a></li>
          {% else %}
          <li ><a href="{% url 'travel:register'%}">Sign Up</a> <span class="arrow"></span>
          </li>
          <li><a href="{% url 'travel:login'%}">Sign In</a></li>
          {% endif %}
        </ul>

    </div>
  </div>
</nav>
</header>
<!--<h1>Book index</h1>-->
<link rel="stylesheet" href="{% static 'css/style.css' %}" type = 'text/css'/>
<link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css"/>

<section id="banner" class="parallex-bg section-padding">
  <div class="container">
    <div class="intro_text white-text div_zindex">
      <h1>Welcome to TravelMate</h1>
      <h4>Ride Sharing Application</h4>
      <div class="search_form">
        <div style="padding-left:30%;padding-right:30%">
          {% if request.session.userid %}
          <a href ="{% url 'offer:index' request.session.userid %}"> <input type="submit"   value="Offer a ride" class="btn btn-block"></a>
          {% else %}
          <a href ="{% url 'travel:login'%}"> <input type="submit"   value="Offer a ride" class="btn btn-block"></a>
          {% endif %}
          &nbsp;   <p >OR</p>
          {% if request.session.userid %}
          <a href ="{% url 'book:index' request.session.userid %}"><input type="submit" href ='/book' value="Book a ride" class="btn btn-block"></a>
          {% else %}
          <a href ="{% url 'travel:login'%}"> <input type="submit"   value="Book a ride" class="btn btn-block"></a>
          {% endif %}
          &nbsp;
        </div>
      </div>
    </div>
  </div>
  <div class="dark-overlay"></div>
</section>

<section id="about_info" class="section-padding">
  <div class="container">
    <div class="row">
      <div class="col-sm-5" ><img src="{%static 'images/neu.png'%}" style="margin:auto;width:50%;display:block;margin-top:15%" /></div>
      <div class="col-sm-2" ></div>
      <div class="col-sm-5" ><h2>By Northeastern. </h2>
        <h2>For Northeastern!</h2>
        <p>Save time and hassle. Catch a ride with your fellow Huskies! You can either look for a ride or just offer your ride to share it with your fellow huskies!</p></div>

      </div>
    </div>
  </section>

travel/templates/travel/login.html
<!DOCTYPE html>
<html lang="en">
<head>
	<title>Login</title>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
<!--===============================================================================================-->
{%load staticfiles %}

	<link rel="icon" type="image/png" href="{%static 'images/icons/favicon.ico' %}"/>
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href=" {%static 'vendor/bootstrap/css/bootstrap.min.css' %}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{%static 'fonts/font-awesome-4.7.0/css/font-awesome.min.css' %}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{%static 'fonts/iconic/css/material-design-iconic-font.min.css' %}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{%static 'vendor/animate/animate.css' %} ">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{%static 'vendor/css-hamburgers/hamburgers.min.css' %}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{%static 'vendor/animsition/css/animsition.min.css' %}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{%static 'vendor/select2/select2.min.css' %}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{%static 'vendor/daterangepicker/daterangepicker.css' %}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{%static 'css/util.css' %}">
	<link rel="stylesheet" type="text/css" href="{%static 'css/main.css' %}">
<!--===============================================================================================-->
</head>
<body>

	<div class="limiter">
		<div class="container-login100">
			<div class="wrap-login100">
				{{error}}
				<form class="login100-form validate-form" action="{% url 'travel:loginsubmit' %}" method="post" class="login100-form validate-form">
					{% csrf_token %}
					<span class="login100-form-title p-b-48">
						TRAVELMATE
					</span>

					<div class="wrap-input100 validate-input" data-validate = "Valid email is: a@b.c">
						<input class="input100" type="text" name="mail">
						<span class="focus-input100" data-placeholder="Email"></span>
					</div>

					<div class="wrap-input100 validate-input" data-validate="Enter password">
						<span class="btn-show-pass">
							<i class="zmdi zmdi-eye"></i>
						</span>
						<input class="input100" type="password" name="password">
						<span class="focus-input100" data-placeholder="Password"></span>
					</div>

					<div class="container-login100-form-btn">
						<div class="wrap-login100-form-btn">
							<div class="login100-form-bgbtn"></div>
							<button class="login100-form-btn" type="submit">
								Login
							</button>
							<!--<input class="login100-form-btn" type="submit" value="Login">-->
						</div>
						<a class="txt2" href="{% url 'travel:index' %}" style="padding-top:10%">Cancel</a>
					</div>

					<div class="text-center p-t-65">
						<span class="txt1">
							Don’t have an account?
						</span>

						<a class="txt2" href="{% url 'travel:register'%}">Sign Up</a>
					</div>
				</form>
			</div>
		</div>
	</div>


	<div id="dropDownSelect1"></div>

<!--===============================================================================================-->
	<script src="{%static 'vendor/jquery/jquery-3.2.1.min.js'%}"></script>
<!--===============================================================================================-->
	<script src="{%static 'vendor/animsition/js/animsition.min.js'%}"></script>
<!--===============================================================================================-->
	<script src="{%static 'vendor/bootstrap/js/popper.js'%}"></script>
	<script src="{%static 'vendor/bootstrap/js/bootstrap.min.js'%}"></script>
<!--===============================================================================================-->
	<script src="{%static 'vendor/select2/select2.min.js' %}"></script>
<!--===============================================================================================-->
	<script src="{%static 'vendor/daterangepicker/moment.min.js'%}"></script>
	<script src="{%static 'vendor/daterangepicker/daterangepicker.js'%}"></script>
<!--===============================================================================================-->
	<script src="{%static 'vendor/countdowntime/countdowntime.js'%}"></script>
<!--===============================================================================================-->
	<script src="{%static 'js/main.js' %}"></script>

</body>
</html>

travel/templates/travel/register.html
<!--
	Author: W3layouts
	Author URL: http://w3layouts.com
	License: Creative Commons Attribution 3.0 Unported
	License URL: http://creativecommons.org/licenses/by/3.0/
-->
<!DOCTYPE html>
<html>
<head>
<title>TravelMate</title>
<!-- Meta tag Keywords -->
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
{%load staticfiles %}
<script type="application/x-javascript"> addEventListener("load", function() { setTimeout(hideURLbar, 0); }, false);
function hideURLbar(){ window.scrollTo(0,1); } </script>
<link href="{%static 'css/reg.css'%}" rel="stylesheet" type="text/css" media="all">
<link href="{%static 'css/font-awesome.min.css'%}" rel="stylesheet" type="text/css" media="all">
<!-- //css files -->
<!-- online-fonts -->
<link href='https://fonts.googleapis.com/css?family=Lato:400,100,100italic,300,300italic,400italic,700,700italic,900,900italic' rel='stylesheet' type='text/css'>
<link href='https://fonts.googleapis.com/css?family=Raleway+Dots' rel='stylesheet' type='text/css'>
	<link rel="stylesheet" type="text/css" href="{%static 'css/main.css' %}">
	<link rel="stylesheet" type="text/css" href="{%static 'fonts/iconic/css/material-design-iconic-font.min.css' %}">

	<link rel="stylesheet" type="text/css" href="{%static 'css/main.css' %}">

</head>
<body>
<!--header-->

<!--//header-->
<!--main-->
<!--<div class="main-agileits">
	<h2 class="sub-head">Sign Up</h2>
		<div class="sub-main">
			<form action="{% url 'travel:registersubmit' %}" method="post">
        {% csrf_token %}
				<input placeholder="First Name" name="fname" class="name" type="text" required="">
					<span class="icon1"><i class="fa fa-user" aria-hidden="true"></i></span><br>
				<input placeholder="Last Name" name="lname" class="name2" type="text" required="">
					<span class="icon2"><i class="fa fa-user" aria-hidden="true"></i></span><br>
				<input placeholder="Phone Number" name="number" class="number" type="text" required="">
					<span class="icon3"><i class="fa fa-phone" aria-hidden="true"></i></span><br>
				<input placeholder="Email" id="txtEmail" name="mail" class="mail" type="text" onblur="checkEmail();" required="true">
				<span id="emailError" class="confirmMessage"></span>
					<span class="icon4"><i class="fa fa-envelope" aria-hidden="true"></i></span><br>
				<input  placeholder="Password" id="password" class="pass" type="password" required="true">
					<span class="icon5"><i class="fa fa-unlock" aria-hidden="true"></i></span><br>
				<input  placeholder="Confirm Password" id="confirmpassword" class="pass" type="password" onblur="checkSame(); return false;" required="true">

					<span class="icon6"><i class="fa fa-unlock" aria-hidden="true"></i></span><br>
					<span id="confirmMessage" class="confirmMessage"></span>

				<input type="submit" value="sign up">
			</form>
		</div>
		<div class="clear"></div>
</div>
<!--//main-->
<div class="limiter">
		<div class="container-login100">
			<div class="wrap-login100">
				{{error}}
				<form class="login100-form validate-form" action="{% url 'travel:registersubmit' %}" method="post">
					{% csrf_token %}
					<span class="login100-form-title p-b-48">
						TRAVELMATE
					</span>
					<div class="wrap-input100 validate-input" >
						<input class="input100" type="text" name="fname" required>
						<span class="focus-input100" data-placeholder="First Name"></span>
					</div>
					<div class="wrap-input100 validate-input" >
						<input class="input100" type="text" name="lname" required>
						<span class="focus-input100" data-placeholder="Last Name"></span>
					</div>
					<div class="wrap-input100 validate-input" >
						<input type="tel" name="number" class="input100" pattern="[0-9]{10}"  onKeyDown="if(this.value.length==10 && event.keyCode!=8) return false;" required/>
						<!--<input  name="text" class="input100" type="number" maxlength="10">-->
						<span class="focus-input100" data-placeholder="Phone Number"></span>
					</div>

					<div class="wrap-input100 validate-input" data-validate = "Valid email is: a@b.c">
						<input  class="input100" id="txtEmail" name="mail" class="mail" type="text" onblur="checkEmail();" required>
						<span class="focus-input100" data-placeholder="Email (Husky Id)"></span>
					</div>

					<div class="wrap-input100 validate-input" data-validate="Enter password">
						<span class="btn-show-pass">
							<i class="zmdi zmdi-eye"></i>
						</span>
						<input class="input100" type="password" name="password" id="password" required>
						<span class="focus-input100" data-placeholder="Password"></span>
					</div>
					<div class="wrap-input100 validate-input" data-validate="Enter password">
						<span class="btn-show-pass">
							<i class="zmdi zmdi-eye"></i>
						</span>
						<input class="input100" type="password" name="confirmpassword" id="confirmpassword" onblur="checkSame(); return false;" required>
						<span class="focus-input100" data-placeholder="Confirm Password"></span>
					</div>
					<span id="confirmMessage" class="confirmMessage"></span>
					<div class="container-login100-form-btn">
						<div class="wrap-login100-form-btn">
							<div class="login100-form-bgbtn"></div>
							<button class="login100-form-btn" type="submit" value="sign up">
								Sign Up
							</button>
							<!--<input class="login100-form-btn" type="submit" value="Login">-->
						</div>
						<a class="txt2" href="{% url 'travel:index' %}" style="padding-top:10%">Cancel</a>
					</div>

					<div class="text-center p-t-65" style="padding-top:10%">
						<span class="txt1">
							Already have an account?
						</span>

						<a class="txt2" href="{% url 'travel:login'%}">Log In</a>
					</div>
				</form>
			</div>
		</div>
	</div>

</body>
<script>
    function checkEmail() {
    	var message = document.getElementById('confirmMessage');
    	var goodColor = "#ff6666";
        var email = document.getElementById('txtEmail');
        var filter = /^\w+[\+\.\w-]*@*(\husky.neu.edu)+$/;
        if (!filter.test(email.value)) {
         	//email.style.border = "2px solid Red";
            message.innerHTML = "Please provide a valid Husky Id!"
            message.style.color = goodColor;
            email.value="";
            return false;
        }
        else {
        	//alert('Valid ');
        	}
    }
</script>
<script>
    function checkSame()
{
    //Store the password field objects into variables ...
    var password = document.getElementById('password');
    var confirmpassword = document.getElementById('confirmpassword');
    //Store the Confimation Message Object ...
    var message = document.getElementById('confirmMessage');
    //Set the colors we will be using ...
    var goodColor = "#ff6666";
    var badColor = "#ffffff";
    //Compare the values in the password field
    //and the confirmation field
     if(password.value != confirmpassword.value && confirmpassword.value !=""){
        //The passwords match.
        //Set the color to the good color and inform
        //the user that they have entered the correct password
        //confirmpassword.style.border = "2px solid Red";
        message.style.color = goodColor;
        message.innerHTML = "Password cannot be different!"
        password.value="";
        confirmpassword.value="";

    }else{
        //The passwords do not match.
        //Set the color to the bad color and
        //notify the user.
        password.style.border = "";
        confirmpassword.style.backgroundColor = "";
        message.innerHTML = "";
    }
}
</script>
<!--===============================================================================================-->
	<script src="{%static 'vendor/jquery/jquery-3.2.1.min.js'%}"></script>

<!--===============================================================================================-->
	<script src="{%static 'js/main.js' %}"></script>

</html>