TravelMate/urls.py
from django.conf.urls import include,url
from django.contrib import admin

urlpatterns = [
    # first landing page - /
    url(r'^', include('travel.urls')),
    #admin url - /admin
    url(r'^admin/', admin.site.urls),
    #book url - /book
    url(r'^book/', include('book.urls')),
    #offer url - /offer
    url(r'^offer/', include('offer.urls')),
    #myride url - /myride
    url(r'^myride/', include('myride.urls')),
]

book/urls.py
from django.conf.urls import url
from . import views

app_name = 'book'

urlpatterns = [
    #/book/<userid>/
    url(r'^(?P<userid>[0-9]+)/$', views.index, name = 'index'),
    #/book/<userid>/search
    url(r'^(?P<userid>[0-9]+)/search/', views.searchres, name = 'searchres'),
    #/book/<userid>/bookdetails
    url(r'^(?P<userid>[0-9]+)/bookdetails/', views.bookdetails, name = 'bookdetails'),
]

offer/urls.py
from django.conf.urls import url
from . import views

app_name = 'offer'

urlpatterns = [
    #/offer/<userid>/
    url(r'^(?P<userid>[0-9]+)/$', views.index, name = 'index'),
    #/offer/<userid>/offerdetails
    url(r'^(?P<userid>[0-9]+)/offerdetails/', views.offerdetails, name = 'offerdetails'),
    #/offer/<userid>/delete
    url(r'^(?P<userid>[0-9]+)/delete/', views.deleteride, name = 'deleteride'),
    #/offer/<userid>/offerings
    url(r'^(?P<userid>[0-9]+)/offerings/', views.allofferedrides, name = 'allofferedrides'),
]

travel/urls.py
from django.conf.urls import url
from . import views

app_name = 'travel'

urlpatterns = [
    #/
    url(r'^$', views.index, name = 'index'),
    #/login
    url(r'^login/', views.login, name = 'login'),
    #/login
    url(r'^loginsubmit/', views.loginsubmit, name = 'loginsubmit'),
    #/register
    url(r'^register/', views.register, name = 'register'),
    #/registersubmit
    url(r'^registersubmit/', views.registersubmit, name = 'registersubmit'),
    #/signout
    url(r'^signout/', views.logout_view, name = 'signout'),
]

offer/models.py
from __future__ import unicode_literals

from django.db import models
from travel.models import User

class Enlist(models.Model):
    uid = models.ForeignKey(User, on_delete = models.CASCADE)
    car_model = models.CharField(max_length = 250)
    car_no = models.IntegerField()
    seat = models.IntegerField()
    from_loc = models.CharField(max_length = 250)
    to_loc = models.CharField(max_length = 250)
    fare = models.FloatField(default=5.0)
    start_time = models.TimeField()
    return_time = models.TimeField()
    start_date = models.DateField()

    def __str__(self):
        return self.from_loc + '-' + self.car_model

offer/views.py
from django.shortcuts import render,get_object_or_404
from .models import Enlist
from travel.models import User
from datetime import datetime


def index(request,userid):
    context = {'userid':userid}
    if request.session.has_key('userid') and request.session['userid'] == int(userid):
        return render(request,'offer/offerindex.html', context)
    else:
        return render(request,'travel/index.html')


def offerdetails(request,userid):
    if request.session.has_key('userid') and request.session['userid'] == int(userid):
        user = get_object_or_404(User,pk = userid)
        ent = Enlist()
        ent.uid = user
        ent.car_model =request.POST.get('car')
        ent.car_no = request.POST.get('car_no')
        ent.seat = request.POST.get('seats')
        ent.from_loc = request.POST.get('fromlocation')
        ent.to_loc = request.POST.get('tolocation')
        ent.fare = request.POST.get('fare')
        ent.start_time =request.POST.get('start_time')
        #print request.POST.get('return_time')
        ent.return_time =request.POST.get('return_time') # TODO needs to be changed later
        startdate = request.POST.get('start_date')
        parsed_date = datetime.strptime(str(startdate), "%m/%d/%Y")
        ent.start_date = parsed_date
        ent.save()
        all_enlists = Enlist.objects.filter(uid = user)
        #print all_enlists
        context = {'all_enlists':all_enlists}
        return render(request,'offer/offerdetails.html',context)
    else:
        return render(request,'travel/index.html')

def deleteride(request,userid):
    if request.session.has_key('userid') and request.session['userid'] == int(userid):
        enlistid = request.POST.get('eid')
        #print enlistid
        user = get_object_or_404(User,pk = userid)
        if enlistid:
            Enlist.objects.filter(pk = enlistid).delete()
            all_enlists = Enlist.objects.filter(uid = user)
            #print all_enlists
            context = {'all_enlists':all_enlists}
            return render(request,'offer/offerdetails.html',context)
    else:
        return render(request,'travel/index.html')

def allofferedrides(request,userid):
    if request.session.has_key('userid') and request.session['userid'] == int(userid):
        user = get_object_or_404(User,pk = userid)
        all_enlists = Enlist.objects.filter(uid = user)
        context = {'all_enlists':all_enlists}
        return render(request,'offer/offerdetails.html',context)

offer/templates/offer/offerdetails.html
{%load staticfiles %}
{% csrf_token %}
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <title>Offer ride details</title>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
  <link href='//fonts.googleapis.com/css?family=Lobster&subset=latin,latin-ext' rel='stylesheet' type='text/css'>
  <link rel="stylesheet" href="{% static 'css/offerdetails.css' %}" type="text/css">
  <link rel="stylesheet" href="{% static 'css/style.css' %}" type="text/css">
  <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}" type="text/css">
  <link rel="stylesheet" href="{% static 'css/owl.carousel.css' %}" type="text/css">
  <link rel="stylesheet" href="{% static  'css/font-awesome.min.css' %}" type="text/css">
  <link href="https://fonts.googleapis.com/css?family=Montserrat:300,400,500,700,800" rel="stylesheet">
  <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,400,600,700" rel="stylesheet">
</head>

<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
<script>
$(document).ready(function(){
    $(".cancelbtn").click(function(){
        $(".removecard").remove();
    });
});

</script>

<body>
  <header id="header">

    <nav class="navbar navbar-default navbar-fixed-top" data-spy="affix" data-offset-top="10">
      <div class="float-left"> <a href="{% url 'travel:index' %}"><img src="{% static 'images/logo1.png'%}" alt="image"/></a> </div>
      <div class="container">
        <div class="navbar-header">

          <button id="menu_slide" data-target="#navigation" aria-expanded="false" data-toggle="collapse" class="navbar-toggle collapsed" type="button">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
        </div>
        <div class="collapse navbar-collapse" id="navigation">
          <ul class="nav navbar-nav">
            <!--<li class="menu-item-has-children"><a href="#">User Panel</a> <span class="arrow"></span>
            <ul class="sub-menu">
            <li><a href="dashboard.html">Dashboard</a></li>
            <li><a href="dashboard-my-listings.html">My Listings</a></li>
            <li><a href="dashboard-reviews.html">Reviews</a></li>
            <li><a href="dashboard-bookmarks.html">Bookmarks</a></li>
            <li><a href="blog-single.html">Add Listing</a></li>
            <li><a href="dashboard-my-profile.html">My Profile</a></li>
          </ul>
        </li>-->
        <li ><a href="#">{{request.session.username}}</a> <span class="arrow"></span>
          <ul class="sub-menu">
            <li><a href="/myride">My Rides</a></li>
            <!--<li><a href="#">My Profile</a></li>-->
            <li><a href="{% url 'travel:signout'%}">Sign Out</a></li>
          </ul>
        </li>

        <!--<li><a href="signin.html">Sign In</a></li>-->
      </ul>
      <div class="submit_listing">
        <a href="{% url 'book:index' request.session.userid %}" class="btn outline-btn"><!--<i class="fa  fa-plus-circle"></i>-->Book a ride</a>
      </div>
    </div>
  </div>
</nav>
</header>


<div class="container">
  <div class="intro_text white-text div_zindex">
    <h1>Welcome to TravelMate</h1>
    <h4>Ride Sharing Application</h4>
    {% csrf_token %}

  </div>
  <div class="ride details">
    <h3 style="color:#000;text-align: center;">My Current Enlisted Rides</h3>
    {% for enlist in all_enlists %}
    <div class="card bg-light mb-3 removecard">
      <div class="card-block ">
        <div class="card-body"><strong>Enlist Id: </strong>{{enlist.id}}</div>
        <div class="card-body"><strong>Start Date: </strong> {{enlist.start_date}}</div>
        <div class="card-body"><strong>Start Time: </strong> {{enlist.start_time}}</div>
        <div class="card-body"><strong>Return Time: </strong> {{enlist.return_time}}</div>
        <div class="card-body"><strong>From : </strong> {{enlist.from_loc}}</div>
        <div class="card-body"><strong>To : </strong> {{enlist.to_loc}}</div>
        <div class="card-body"><strong>Car Model: </strong> {{enlist.car_model}}</div>
        <div class="card-body"><strong>Car No: </strong> {{enlist.car_no}}</div>

        <div class=" text-right">
          <form action="{% url 'offer:deleteride' request.session.userid %}" method="post">
          {% csrf_token %}
            <input type="hidden" name="eid" class="form-control" value={{enlist.id}}>
            <input type="submit" value="Remove" class="btn btn-danger">
          </form>
        </div>
        </div>
       <!-- <div class="card-block, text-right">
            <button id="demo" class="btn btn-success confirmcrd" onclick="myFunction()" data-toggle="modal" data-target="#myModal">Confirm</button>
        </div>-->
      </div>
      {% endfor %}

    <!--<a href ="/" ><button type="button" class="btn btn-success" > Home</button></a>-->
    </div>
  </div>
<div class="container">
 <!-- Modal -->
  <div class="modal fade" id="myModal" role="dialog">
    <div class="modal-dialog">

      <!-- Modal content-->
      <div class="modal-content">
        <div class="modal-header">
          <!--<button type="button" class="close" data-dismiss="modal">&times;</button>-->
          <h4 class="modal-title"></h4>
        </div>
        <div class="modal-body">
          <p>Are you sure to remove your listing?</p>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-default cancelbtn" data-dismiss="modal">Confirm</button>
          <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
        </div>
      </div>

    </div>
  </div>

</div>
</body>
<script>
function myFunction() {
    document.getElementById("demo").style.background = "grey";
    document.getElementById("demo").textContent = "Confirmed";
}
</script>

<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
</html>

offer/templates/offer/offerindex.html
{%load staticfiles %}


<!--Bootstrap -->
<link rel="stylesheet" href="static/css/bootstrap.min.css" type="text/css">
<!--Custome Style -->
<link rel="stylesheet" href="static/css/style.css" type="text/css">
<!--OWL Carousel slider-->
<link rel="stylesheet" href="static/css/owl.carousel.css" type="text/css">
<!--FontAwesome Font Style -->
<link href="static/css/font-awesome.min.css" rel="stylesheet">


<!--Date Picker-->
    <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js"> </script>
<link rel="stylesheet" href="https://jonthornton.github.io/jquery-timepicker/jquery.timepicker.css">
    <link rel="stylesheet" href="https://ajax.googleapis.com/ajax/libs/jqueryui/1.11.3/themes/blitzer/jquery-ui.css" />
    <script src="https://ajax.googleapis.com/ajax/libs/jqueryui/1.11.3/jquery-ui.min.js">
    </script>
    <script src="https://jonthornton.github.io/jquery-timepicker/jquery.timepicker.js">
    </script>

    <script>
    (function($) {
    $(function() {
        $("input.timepicker").timepicker({ 'timeFormat': 'H:i' });
    });
    })(jQuery);
    </script>

    <script>
    (function($) {
    $(function() {
        $("input.timepicker1").timepicker({ 'timeFormat': 'H:i' });
    });
    })(jQuery);
    </script>



<!-- Google-Font-->
<link href="https://fonts.googleapis.com/css?family=Montserrat:300,400,500,700,800" rel="stylesheet">
<link href="https://fonts.googleapis.com/css?family=Open+Sans:300,400,600,700" rel="stylesheet">
<header id="header">
    <nav class="navbar navbar-default navbar-fixed-top" data-spy="affix" data-offset-top="10">
        <div class="container">
            <div class="navbar-header">
                <div class="logo"><a href="{% url 'travel:index' %}"><img src="{%static 'images/logo1.png'%}"
                                                                          alt="image"/></a></div>
                <button id="menu_slide" data-target="#navigation" aria-expanded="false" data-toggle="collapse"
                        class="navbar-toggle collapsed" type="button">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
            </div>
            <div class="collapse navbar-collapse" id="navigation">
                <ul class="nav navbar-nav">
                    <!--<li class="menu-item-has-children"><a href="#">User Panel</a> <span class="arrow"></span>
                    <ul class="sub-menu">
                    <li><a href="dashboard.html">Dashboard</a></li>
                    <li><a href="dashboard-my-listings.html">My Listings</a></li>
                    <li><a href="dashboard-reviews.html">Reviews</a></li>
                    <li><a href="dashboard-bookmarks.html">Bookmarks</a></li>
                    <li><a href="blog-single.html">Add Listing</a></li>
                    <li><a href="dashboard-my-profile.html">My Profile</a></li>
                  </ul>
                </li>-->
                    <li><a href="#">{{request.session.username}}</a> <span class="arrow"></span>
                        <ul class="sub-menu">
                            <li><a href="/myride">My Rides</a></li>
                            <!--<li><a href="#">My Profile</a></li>-->
                            <li><a href="{% url 'offer:allofferedrides' request.session.userid%}">My Offerings</a></li>
                            <li><a href="{% url 'travel:signout'%}">Sign Out</a></li>
                        </ul>
                    </li>

                    <!--<li><a href="signin.html">Sign In</a></li>-->
                </ul>
                <div class="submit_listing">
                    <a href="{% url 'book:index' request.session.userid %}" class="btn outline-btn"><!--<i class="fa  fa-plus-circle"></i>-->Book a ride</a>
                </div>
            </div>
        </div>
    </nav>
</header>

<!--<h1>Book index</h1>-->
<link rel="stylesheet" href="{% static 'css/style.css' %}" type='text/css'/>
<link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css"/>


<div class="container">
    <div class="intro_text white-text div_zindex">
      <form action="{% url 'offer:offerdetails' userid %}" method="post">
        {% csrf_token %}
        <div class="" style="padding-top:8%">

            <!--<div class="form-group select">
            <select class="form-control">
            <option>Where are you?</option>
            <option>Northeastern University</option>
            <option>Downtown</option>
            <option></option>
            <option>Health & Fitness</option>
            <option>Beauty & Spas</option>
            <option>Hotels & Travel</option>
            <option>Automotive</option>
          </select>
        </div>-->
            <h3 style="color:#000;text-align: center;">Offer your Ride</h3>


            <div class="idealforms add-ride" style="text-align: center;">
                <h5 style="color:#000;padding-left:1em;padding-top:1em"></h5>
                <input type="text" id="fromlocation" name = "fromlocation" class="form-control"  placeholder="Leaving From" required>
            </div>
            <div class="idealforms add-ride">
                <h5 style="color:#000;padding-left:1em;padding-top:1em"></h5>
                <input type="text" id="tolocation" name = "tolocation" class="form-control" placeholder="Going To" onblur="checkSame(); return false;" required>
            </div>
            <span id="confirmMessage" class="confirmMessage"></span>
            <div style="width: 100%; display: table;">
                <div style="display: table-row">
                    <div class="idealforms add-ride" style="width:  25%; display: table-cell;">
                        <h5 style="color:#000;padding-left:1em;padding-top:1em;">Start Date</h5>
                        <p> <input  id="departure"  name = "start_date" style="color:Black" required></p>
                    </div>

                    <div style="width:12%"></div>
                    <div class="idealforms add-ride" style="width:  25%; display: table-cell;">
                        <h5 style="color:#000;padding-left:1em;padding-top:1em">Start Time</h5>
                        <p> <input  type="text" class="timepicker1" name="start_time"  style="color:Black;" required></p>
                    </div>
                    <!-- <div class="idealforms add-ride" style="width:  30%; display: table-cell;">
                        <h5 style="color:#000;padding-left:1em;padding-top:1em">Start Time</h5>
                        <p> <input  id="timeFrom"  style="color:Black"></p>
                    </div> -->
                    <div style="width: 12%"></div>
                    <!-- TODO return_time issue-->

                    <div class="idealforms add-ride" style="width:  25%; display: table-cell;">
                        <h5 style="color:#000;padding-left:1em;padding-top:1em">Return Time</h5>
                            <p>  <input  type="text" class="timepicker1" name="return_time" style="color:Black;" required></p>
                    </div>
                    <!--<div class="idealforms add-ride" style="width:  30%; display: table-cell;">
                        <h5 style="color:#000;padding-left:1em;padding-top:1em">Return Time</h5>
                        <p> <input  id="timeTo"  style="color:Black"></p>
                    </div>-->



                    <!--<div class="idealforms add-ride" style="width: 45%; display: table-cell;">
                        <h5 style="color:#000;padding-left:1em;padding-top:1em">End Date</h5>
                        <input type="date" id="enddate1" class="form-control" placeholder="Date">
                    </div>-->
                </div>
            </div>

            <div style="width: 100%; display: table;">
                <div class="idealforms add-ride" style="width: 45%; display: table-cell;">
                    <h5 style="color:#000;padding-left:1em;padding-top:1em">Car Model</h5>
                    <select name="car" class="form-control">
                        <option value="Volkswagen Golf">Volkswagen Golf</option>
                        <option value="Ford Fiesta">Ford Fiesta</option>
                        <option value="Toyota Corolla">Toyota Corolla</option>
                        <option value="BMW M4">BMW M4</option>
                        <option value="Ford Escape">Ford Escape</option>
                        <option value="Subaru">Subaru</option>
                    </select>
                </div>
                <div style="width=10%"></div>

                <div class="idealforms add-ride" style="width: 45%; display: table-cell;">
                    <h5 style="color:#000;padding-left:1em;padding-top:1em">License Plate No</h5>
                    <input type="number" id="licensenumber" name = "car_no" class="form-control" onkeydown="javascript: return event.keyCode == 69 ? false : true" required>
                </div>
            </div>


            <div style="width: 100%; display: table;">
                <div class="idealforms add-ride" style="width:  45%; display: table-cell;">
                    <h5 style="color:#000;padding-left:1em;padding-top:1em">No of Seats</h5>
                    <select name="seats" class="form-control">
                        <option value="1">1</option>
                        <option value="2">2</option>
                        <option value="3">3</option>
                        <option value="4">4</option>

                    </select>
                </div>

                <div style="width=10%"></div>
                <div class="idealforms add-ride" style="width:  45%; display: table-cell;">
                    <h5 style="color:#000;padding-left:1em;padding-top:1em">Monthly Fare</h5>
                    <input type="number" id="fare" name = "fare" min="0.0" step="1" class="form-control" placeholder="Enter Monthly Fare/Seat ($)" required>
                </div>
            </div>

                <h5 style="color:#000; padding-left:1em; padding-top:1em"></h5>
                <div style="width: 100%; padding-top:3%;display: table;">
                    <div class="idealforms add-ride" style="width:  45%;padding-left: 30%; display: table-cell;">
                        <a href="/"> <input value="Cancel"  class="btn btn-block" style="background:Red; padding: 1.2em "></a>
                    </div>
                    <div style="width=0%"></div>
                     <div class="idealforms add-ride" style="width:45%;padding-right: 30%; display: table-cell;">
                        <input type="submit" value="Post a Ride" class="btn btn-block">
                     </div>
                 </div>
            </form>
            <br>



            <h5 style="color:#000; padding-left:1em; padding-top:1em"></h5>
        </div>
    </div>
</div>



<!--<script type="text/javascript">
    var formSubmitting = false;
var setFormSubmitting = function() { formSubmitting = true; };

window.onload = function() {
    window.addEventListener("beforeunload", function (e) {
        if (formSubmitting) {
            return undefined;
        }

        var confirmationMessage = 'It looks like you have been editing something. '
                                + 'If you leave before saving, your changes will be lost.';

        (e || window.event).returnValue = confirmationMessage; //Gecko + IE
        return confirmationMessage; //Gecko + Webkit, Safari, Chrome etc.
    });
};




</script>-->
<script>
    $(function(){
      $("#departure").datepicker({
        showAnim: "fadeIn",
        changeYear: true,
        numberOfMonths: 1,
        dateFormat: "mm/dd/yy",

        minDate: +1,
        maxDate: "+12M +10D",
        onClose: function(selectedDate){
          $("#return").datepicker("option", "minDate", selectedDate)
        }
        ,
        showWeek: true
      });
    });

  </script>


  <script>
  $(function(){
  $("#fromlocation").autocomplete({
  source: ["Boston","Chicago","California","London","San Francisco","London",
      "Northeastern University", "Burlington", "Andover", "Paris", "Paris", "Paris", "Madrid", "Madrid", "Madrid",
      "Madrid", "Madrid"]
  });
  });
   </script>
<script>
  $(function(){
  $("#tolocation").autocomplete({
  source: ["Boston","Chicago","California","London","San Francisco","London",
      "Northeastern University", "Burlington", "Andover", "Paris", "Paris", "Paris", "Madrid", "Madrid", "Madrid",
      "Madrid", "Madrid"]
  });
  });
   </script>
<script>
    function checkSame()
{
    //Store the password field objects into variables ...
    var fromlocation = document.getElementById('fromlocation');
    var tolocation = document.getElementById('tolocation');
    //Store the Confimation Message Object ...
    var message = document.getElementById('confirmMessage');
    //Set the colors we will be using ...
    var goodColor = "#ff6666";
    var badColor = "#ffffff";
    //Compare the values in the password field
    //and the confirmation field
     if(fromlocation.value == tolocation.value && tolocation.value !=""){
        //The passwords match.
        //Set the color to the good color and inform
        //the user that they have entered the correct password
        tolocation.style.border = "2px solid Red";
        message.style.color = goodColor;
        message.innerHTML = "Location cannot be Same!"
    }else{
        //The passwords do not match.
        //Set the color to the bad color and
        //notify the user.
        tolocation.style.border = "";
        tolocation.style.backgroundColor = badColor;
        message.innerHTML = "";
    }
}
</script>