TravelMate/urls.py
from django.conf.urls import include,url
from django.contrib import admin

urlpatterns = [
    # first landing page - /
    url(r'^', include('travel.urls')),
    #admin url - /admin
    url(r'^admin/', admin.site.urls),
    #book url - /book
    url(r'^book/', include('book.urls')),
    #offer url - /offer
    url(r'^offer/', include('offer.urls')),
    #myride url - /myride
    url(r'^myride/', include('myride.urls')),
]

book/urls.py
from django.conf.urls import url
from . import views

app_name = 'book'

urlpatterns = [
    #/book/<userid>/
    url(r'^(?P<userid>[0-9]+)/$', views.index, name = 'index'),
    #/book/<userid>/search
    url(r'^(?P<userid>[0-9]+)/search/', views.searchres, name = 'searchres'),
    #/book/<userid>/bookdetails
    url(r'^(?P<userid>[0-9]+)/bookdetails/', views.bookdetails, name = 'bookdetails'),
]

myride/urls.py
from django.conf.urls import url
from . import views

app_name = 'myride'

urlpatterns = [
    #/myride/
    url(r'^$', views.index, name = 'index'),
    url(r'^rate/', views.rate, name = 'rate'),
    # later remove the below two functions and we'll just filter the results on
    # on index page of myride based on start/end date and current date
    url(r'^upcoming/', views.upcoming, name = 'upcoming'),
    url(r'^previous/', views.previous, name = 'previous'),
]

offer/urls.py
from django.conf.urls import url
from . import views

app_name = 'offer'

urlpatterns = [
    #/offer/<userid>/
    url(r'^(?P<userid>[0-9]+)/$', views.index, name = 'index'),
    #/offer/<userid>/offerdetails
    url(r'^(?P<userid>[0-9]+)/offerdetails/', views.offerdetails, name = 'offerdetails'),
    #/offer/<userid>/delete
    url(r'^(?P<userid>[0-9]+)/delete/', views.deleteride, name = 'deleteride'),
    #/offer/<userid>/offerings
    url(r'^(?P<userid>[0-9]+)/offerings/', views.allofferedrides, name = 'allofferedrides'),
]

travel/urls.py
from django.conf.urls import url
from . import views

app_name = 'travel'

urlpatterns = [
    #/
    url(r'^$', views.index, name = 'index'),
    #/login
    url(r'^login/', views.login, name = 'login'),
    #/login
    url(r'^loginsubmit/', views.loginsubmit, name = 'loginsubmit'),
    #/register
    url(r'^register/', views.register, name = 'register'),
    #/registersubmit
    url(r'^registersubmit/', views.registersubmit, name = 'registersubmit'),
    #/signout
    url(r'^signout/', views.logout_view, name = 'signout'),
]

book/models.py
from __future__ import unicode_literals

from django.db import models
from travel.models import User
from offer.models import Enlist

class Reservation(models.Model):
    uid = models.ForeignKey(User, on_delete = models.CASCADE)
    eid = models.ForeignKey(Enlist, on_delete = models.CASCADE)
    from_loc = models.CharField(max_length = 250)
    to_loc = models.CharField(max_length = 250)
    start_date = models.DateField()
    status = models.BooleanField(default = False)


    def __str__(self):
        return self.from_loc + '-' + self.to_loc

book/views.py
from django.shortcuts import render,get_object_or_404
from .models import Reservation
from offer.models import Enlist
from travel.models import User
from myride.views import upcoming
from datetime import datetime

# get form data here and

def index(request,userid):
    context = {'userid':userid}
    if request.session.has_key('userid') and request.session['userid'] == int(userid):
        return render(request,'book/bookindex.html',context)
    else:
        return render(request,'travel/index.html')




def searchres(request,userid):
    # print(request.POST)
    if request.session.has_key('userid') and request.session['userid'] == int(userid):
        fromlocation = request.POST.get('fromlocation')
        tolocation = request.POST.get('tolocation')
        departure = request.POST.get('departure')
        user_start = request.POST.get('user_start')
        print(user_start)

        context = {'error': 'Enter the details'}
        if departure and fromlocation and tolocation :
            parsed_date = datetime.strptime(str(departure), "%m/%d/%Y")
            all_enlists = Enlist.objects.filter(from_loc=fromlocation,to_loc=tolocation,start_date__lte = parsed_date,seat__gte=1, start_time__gte = user_start).order_by('start_time')
            some_enlists = Enlist.objects.filter(from_loc=fromlocation,to_loc=tolocation,start_date__lte = parsed_date,seat__gte=1, start_time__lt = user_start).order_by('-start_time')
            context = {
                'all_enlists': all_enlists,
                'fromlocation': fromlocation,
                'tolocation': tolocation,
                'departure': departure,
                'user_start': user_start,
                'some_enlists': some_enlists
            }
            #print(departure)
        return render(request,'book/search.html',context)
    else:
        return render(request,'travel/index.html')



def bookdetails(request,userid):
    if request.session.has_key('userid') and request.session['userid'] == int(userid):
        enlistid = request.POST.get('eid')
        user = get_object_or_404(User,pk = userid)
        enlist = get_object_or_404(Enlist,pk = enlistid)
        if enlist.uid.pk != user.pk:
            reservation = Reservation()
            reservation.uid = user
            reservation.eid = enlist
            reservation.from_loc = enlist.from_loc
            reservation.to_loc = enlist.to_loc
            reservation.start_date = enlist.start_date
            reservation.start_time = enlist.start_time
            reservation.return_time = enlist.return_time
            reservation.save()
            seat = enlist.seat
            seat = seat - 1
            enlist.seat = seat
            enlist.save()
            return upcoming(request)
        else:
            context = {
                'error': "Please select an offered ride which is not provided by you.",
                'fromlocation': enlist.from_loc,
                'tolocation': enlist.to_loc
            }
            return render(request, 'book/search.html', context)
    else:
        return render(request,'travel/index.html')

book/templates/book/bookindex.html
<!--<h1>Hello Index page</h1>


<a href ='/book'> Book a ride </a> <br>
<a href ='/offer'> Offer a ride </a><br>
<a href ='/myride'> My Rides </a>-->

{%load staticfiles %}
<!--Bootstrap -->
<link rel="stylesheet" href="static/css/bootstrap.min.css" type="text/css">
<!--Custome Style -->
<link rel="stylesheet" href="static/css/style.css" type="text/css">
<!--OWL Carousel slider-->
<link rel="stylesheet" href="static/css/owl.carousel.css" type="text/css">
<!--FontAwesome Font Style -->
<link href="static/css/font-awesome.min.css" rel="stylesheet">

<!--Date Picker-->
<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js"> </script>

<link rel="stylesheet" href="https://ajax.googleapis.com/ajax/libs/jqueryui/1.11.3/themes/blitzer/jquery-ui.css" />
<script src="https://ajax.googleapis.com/ajax/libs/jqueryui/1.11.3/jquery-ui.min.js">
</script>

<script src="https://jonthornton.github.io/jquery-timepicker/jquery.timepicker.js">
</script>
<link rel="stylesheet" href="https://jonthornton.github.io/jquery-timepicker/jquery.timepicker.css">
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
<!-- Google-Font-->
<link href="https://fonts.googleapis.com/css?family=Montserrat:300,400,500,700,800" rel="stylesheet">
<link href="https://fonts.googleapis.com/css?family=Open+Sans:300,400,600,700" rel="stylesheet">
<header id="header">
  <nav class="navbar navbar-default navbar-fixed-top" data-spy="affix" data-offset-top="10">
    <div class="container">
      <div class="navbar-header">
        <div class="logo"> <a href="{% url 'travel:index' %}"><img src="{%static 'images/logo1.png'%}" alt="image"/></a> </div>
        <button id="menu_slide" data-target="#navigation" aria-expanded="false" data-toggle="collapse" class="navbar-toggle collapsed" type="button">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
      </div>
      <div class="collapse navbar-collapse" id="navigation">
        <ul class="nav navbar-nav">
          <!--<li class="menu-item-has-children"><a href="#">User Panel</a> <span class="arrow"></span>
          <ul class="sub-menu">
          <li><a href="dashboard.html">Dashboard</a></li>
          <li><a href="dashboard-my-listings.html">My Listings</a></li>
          <li><a href="dashboard-reviews.html">Reviews</a></li>
          <li><a href="dashboard-bookmarks.html">Bookmarks</a></li>
          <li><a href="blog-single.html">Add Listing</a></li>
          <li><a href="dashboard-my-profile.html">My Profile</a></li>
        </ul>
      </li>-->
      <li ><a href="#">{{request.session.username}}</a> <span class="arrow"></span>
        <ul class="sub-menu">
          <li><a href="/myride">My Rides</a></li>
          <!--<li><a href="#">My Profile</a></li>-->
          <li><a href="{% url 'offer:allofferedrides' request.session.userid%}">My Offerings</a></li>
          <li><a href="{% url 'travel:signout'%}">Sign Out</a></li>

        </ul>
      </li>

      <!--<li><a href="signin.html">Sign In</a></li>-->
    </ul>
    <div class="submit_listing">
      <a href="{% url 'offer:index' request.session.userid %}" class="btn outline-btn"><!--<i class="fa  fa-plus-circle"></i>-->+ Offer a ride</a>
    </div>
  </div>
</div>
</nav>
</header>
<!--<h1>Book index</h1>-->
<link rel="stylesheet" href="{% static 'css/style.css' %}" type = 'text/css'/>
<link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css"/>

<!--<nav class="navbar navbar-default">
<div class="container-fluid">
<div class="navbar-header"/>
</div>
</nav>-->

<section id="banner" class="parallex-bg section-padding">
  <div class="container">
    <div class="intro_text white-text div_zindex">
      <h1>Welcome to TravelMate</h1>
      <h4>Ride Sharing Application</h4>
      <div class="search_form">

        <!--<div class="form-group select">
        <select class="form-control">
        <option>Where are you?</option>
        <option>Northeastern University</option>
        <option>Downtown</option>
        <option></option>
        <option>Health & Fitness</option>
        <option>Beauty & Spas</option>
        <option>Hotels & Travel</option>
        <option>Automotive</option>
      </select>
    </div>-->


    <!-- IMP PART OF PAGE -->
<!--
    <form method="post">
      {% csrf_token %}
      {{ form.as_p }}
      <button type="submit"> Submit</button>
    </form> -->

    <form action="{% url 'book:searchres' userid %}" method="post">
      {% csrf_token %}
      <div class="form-group">
        <input type="text" name="fromlocation" id = "fromlocation" class="form-control" placeholder="Leaving From" required>
      </div>
      <div class="form-group">
        <input type="text" name="tolocation" id = "tolocation" class="form-control" placeholder="Going To" onblur="checkSame(); return false;" required>
        <span id="confirmMessage" class="confirmMessage"></span>
      </div>

      <div class="form-group">
        <p> <input  name="departure" id="departure"  style="color:Black" placeholder="mm/dd/yyyy" required></p>
        <!--<input type="date" id = "startdate" class="form-control" placeholder="Date">-->
      </div>


      <div class="form-group" >
          <p> <input  type="text" class="timepicker1"  name="user_start" placeholder="Start Time (24 Hrs)" style="color:Black;" required></p>
      </div>

      <div class="form-group search_btn">
        <input type="submit" value="Search"class="btn btn-block"/>
      </div>

    </form>

  </div>
</div>
</div>
<div class="dark-overlay"></div>

</section>



<!-- Popular-Cities/Towns
<section id="popular_cities" class="section-padding">
<div class="container">
<div class="section-header text-center">
<h2>Most Popular Destinations/Towns</h2>
<p>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s.</p>
</div>

<div class="row">
<div class="col-sm-6 col-md-3">
<div class="cities_list">
<div class="city_listings_info">
<h4>Andover</h4>
<div class="listing_number"><span>6 Listings</span> </div>
</div>
<a href="#" class="overlay_link"></a>
</div>
</div>

<div class="col-sm-6 col-md-3">
<div class="cities_list chicago">
<div class="city_listings_info">
<h4>Chicago</h4>
<div class="listing_number"><span>6 Listings</span> </div>
</div>
<a href="#" class="overlay_link"></a>
</div>
</div>

<div class="col-sm-6 col-md-3">
<div class="cities_list angeles">
<div class="city_listings_info">
<h4>Los Angeles</h4>
<div class="listing_number"><span>6 Listings</span> </div>
</div>
<a href="#" class="overlay_link"></a>
</div>
</div>

<div class="col-sm-6 col-md-3">
<div class="cities_list francisco">
<div class="city_listings_info">
<h4>San Francisco</h4>
<div class="listing_number"><span>6 Listings</span> </div>
</div>
<a href="#" class="overlay_link"></a>
</div>
</div>

<div class="col-sm-6 col-md-3">
<div class="cities_list seattle">
<div class="city_listings_info">
<h4>Seattle</h4>
<div class="listing_number"><span>6 Listings</span> </div>
</div>
<a href="#" class="overlay_link"></a>
</div>
</div>

<div class="col-sm-6 col-md-3">
<div class="cities_list washington">
<div class="city_listings_info">
<h4>Washington, D.C.</h4>
<div class="listing_number"><span>6 Listings</span> </div>
</div>
<a href="#" class="overlay_link"></a>
</div>
</div>

<div class="col-sm-6 col-md-3">
<div class="cities_list orlando">
<div class="city_listings_info">
<h4>Orlando</h4>
<div class="listing_number"><span>6 Listings</span> </div>
</div>
<a href="#" class="overlay_link"></a>
</div>
</div>

<div class="col-sm-6 col-md-3">
<div class="cities_list miami">
<div class="city_listings_info">
<h4>Miami</h4>
<div class="listing_number"><span>6 Listings</span> </div>
</div>
<a href="#" class="overlay_link"></a>
</div>
</div>
</div>
<div class="text-center">
<a href="#" class="btn">View More Cities / Towns</a>
</div>
</div>
</section>-->
<section id="about_info" class="section-padding">
  <div class="container">
<div class="row">
  <div class="col-sm-5" ><img src="{%static 'images/neu.png'%}" style="margin:auto;width:50%;display:block;margin-top:15%" /></div>
  <div class="col-sm-2"></div>
  <div class="col-sm-5 " >
    <h3>Some useful tips:</h3>
    <div id="myCarousel" class="carousel slide" data-ride="carousel" style="height:30%;background-color:black">
    <!-- Indicators -->
    <ol class="carousel-indicators">
      <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
      <li data-target="#myCarousel" data-slide-to="1"></li>
      <li data-target="#myCarousel" data-slide-to="2"></li>
    </ol>

    <!-- Wrapper for slides -->
    <div class="carousel-inner" style="width:100%;" >
      <div class="item active">
        <div class="d-block w-100" >
        <h2 style="padding-left:20%;background-color:lavender;width:60%">#Pro Tip 1</h2>

        </div>
        <p style="padding-left:20%;color:white">When in doubt, carry your own music!</p>
      </div>

      <div class="item">
        <div class="d-block w-100" >
        <h2 style="padding-left:10%;background-color:lavenderblush;width:60%">#Pro Tip 2</h2>
        </div>
        <p style="padding-left:10%;color:white">Finding a Travel-Mate is easier than getting a lyft ;)</p>
      </div>

      <div class="item">
        <div class="d-block w-100" >
        <h2 style="padding-left:20%;background-color:lavender;width:60%">#Pro Tip 3</h2>
        </div>
        <p style="padding-left:10%;color:white">Always clean up after completing a ride. Nobody wants your chewingum under their dashboard.</p>
      </div>
    </div>

    <!-- Left and right controls -->
    <a class="left carousel-control" href="#myCarousel" data-slide="prev">
      <span class="glyphicon glyphicon-chevron-left"></span>
      <span class="sr-only">Previous</span>
    </a>
    <a class="right carousel-control" href="#myCarousel" data-slide="next">
      <span class="glyphicon glyphicon-chevron-right"></span>
      <span class="sr-only">Next</span>
    </a>
  </div>
            </div>

  </div>
    </div>
</section>




<script>
$(function(){

  $("#departure").datepicker({
    showAnim: "fadeIn",
    changeYear: true,
    numberOfMonths: 1,
    dateFormat: "mm/dd/yy",
    minDate: +1,
    maxDate: "+12M +10D",
    onClose: function(selectedDate){
      $("#return").datepicker("option", "minDate", selectedDate)
    }
    ,
    showWeek: true
  });


});

</script>

<script>


  $(function(){
  $("#fromlocation").autocomplete({
  source: ["Boston","Chicago","California","London","San Francisco","London",
      "Northeastern University", "Burlington", "Andover","Paris", "Paris", "Madrid",
       "Copley","Wilmington"]
  });
  });


   </script>

    <script>


  $(function(){
  $("#tolocation").autocomplete({
  source: ["Boston","Chicago","California","London","San Francisco","London",
      "Northeastern University", "Burlington", "Andover","Paris", "Paris", "Madrid",
       "Copley","Wilmington"]
  });
  });


   </script>

<script>


  $(function(){
  $("#fromlocation").autocomplete({
  source: ["Boston","Chicago","California","London","San Francisco","London",
      "Northeastern University", "Burlington", "Andover","Paris", "Paris", "Madrid",
       "Copley","Wilmington"]
  });
  });


   </script>

    <script>


  $(function(){
  $("#tolocation").autocomplete({
  source: ["Boston","Chicago","California","London","San Francisco","London",
      "Northeastern University", "Burlington", "Andover","Paris", "Paris", "Madrid",
       "Copley","Wilmington"]
  });
  });


   </script>

   <script>
   (function($) {
   $(function() {
       $("input.timepicker1").timepicker({ 'timeFormat': 'H:i' });
   });
   })(jQuery);
   </script>

<script>
    function checkSame()
{
    //Store the password field objects into variables ...
    var fromlocation = document.getElementById('fromlocation');
    var tolocation = document.getElementById('tolocation');
    //Store the Confimation Message Object ...
    var message = document.getElementById('confirmMessage');
    //Set the colors we will be using ...
    var goodColor = "#ff6666";
    var badColor = "#ffffff";
    //Compare the values in the password field
    //and the confirmation field
     if(fromlocation.value == tolocation.value && tolocation.value !=""){
        //The passwords match.
        //Set the color to the good color and inform
        //the user that they have entered the correct password
        tolocation.style.border = "2px solid Red";
        message.style.color = goodColor;
        message.innerHTML = "Location cannot be Same!"
    }else{
        //The passwords do not match.
        //Set the color to the bad color and
        //notify the user.
        tolocation.style.border = "";
        tolocation.style.backgroundColor = badColor;
        message.innerHTML = "";
    }
}
</script>

book/templates/book/search.html
{%load staticfiles %}
<!--Bootstrap -->
<link rel="stylesheet" href="static/css/bootstrap.min.css" type="text/css">
<!--Custome Style -->
<link rel="stylesheet" href="{% static 'css/style.css' %}" type="text/css">
<!--OWL Carousel slider-->
<link rel="stylesheet" href="static/css/owl.carousel.css" type="text/css">
<!--FontAwesome Font Style -->
<link href="static/css/font-awesome.min.css" rel="stylesheet">
<link href="{% static 'css/accordion.css' %}" rel="stylesheet">
<link rel="stylesheet" href="{% static  'css/rating1.css' %}" type="text/css">



<!-- Google-Font-->
<link href="https://fonts.googleapis.com/css?family=Montserrat:300,400,500,700,800" rel="stylesheet">
<link href="https://fonts.googleapis.com/css?family=Open+Sans:300,400,600,700" rel="stylesheet">
<header id="header">
  <nav class="navbar navbar-default navbar-fixed-top" data-spy="affix" data-offset-top="10">
    <div class="container">
      <div class="navbar-header">
        <div class="logo"><a href="{% url 'travel:index' %}"><img src="{%static 'images/logo1.png'%}"
          alt="image"/></a></div>
          <button id="menu_slide" data-target="#navigation" aria-expanded="false" data-toggle="collapse"
          class="navbar-toggle collapsed" type="button">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
      </div>
      <div class="collapse navbar-collapse" id="navigation">
        <ul class="nav navbar-nav">
      <li><a href="#">{{request.session.username}}</a> <span class="arrow"></span>
        <ul class="sub-menu">
          <li><a href="/myride">My Rides</a></li>
          <li><a href="{% url 'offer:allofferedrides' request.session.userid %}">My Offerings</a></li>
          <li><a href="{% url 'travel:signout'%}">Sign Out</a></li>

        </ul>
      </li>
    </ul>
    <div class="submit_listing">
      <a href="{% url 'offer:index' request.session.userid %}" class="btn outline-btn"><!--<i class="fa  fa-plus-circle"></i>-->+ Offer a ride</a>
    </div>
  </div>
</div>
</nav>
</header>
<!--<h1>Book index</h1>-->
<link rel="stylesheet" href="{% static 'css/style.css' %}" type='text/css'/>
<link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css"/>

<!--<link rel="stylesheet" type="text/css" href="C:/Users/souga/Desktop/TravelMate/book/static/book/style.css"/>-->

<link rel="stylesheet" href="{% static 'css/style.css' %}" type='text/css'/>
<section class="parallex-bg section-padding">

  <div class="text-mid">


    <div class="accordionWrapper" >
      <div class="container" style="width: 100%">
        <div class="search_form">
          <form action="{% url 'book:searchres' request.session.userid %}" method="post">
            {% csrf_token %}
            <div class="form-group" style="width: 15%">
              <input type="text" name="fromlocation" class="form-control" value={{fromlocation}} disabled>
            </div>
            <p style="float: left;width: 3%">&nbsp;</p>
            <div class="form-group" style="width: 15%">
              <input type="text" name="tolocation" class="form-control" value={{tolocation}} disabled>
            </div>

            <p style="float: left;width: 3%">&nbsp;</p>
            <div class="form-group" style="width: 17%">
              <input type="text" name="departure" class="form-control" value={{departure}} disabled>
            </div>
            <p style="float: left;width: 3%">&nbsp;</p>
            <div class="form-group" style="width: 15%">
              <input type="text" name="user_start" class="form-control" value={{user_start}} disabled>
            </div>
            <p style="float: left;width: 3%">&nbsp;</p>
            <div class="form-group search_btn" style="width: 15%">
                 <a href="{% url 'book:index' request.session.userid %}" class="btn btn-block" style="margin-left:2%;">Modify Search</a>
            </div>
          </form>

        </div>
      </div>
       <h4> Search Results </h4>
 {% if all_enlists %}


      <table>


        <tr>
          <th>Start Date</th>
          <th>Ride Offered By</th>
          <th>Car Model</th>
          <th>Fare Price</th>
          <th></th>
        </tr>
        {% for enlist in all_enlists %}

        <tr>

          <td style="width: 10%">{{enlist.start_date}} {{enlist.start_time}}</td>
          <td style="width: 30%;">
            <img src="{% static "images/img_avatar.png" %}" alt="John" style="width:30%; height: 25%">
            <span class="rating">
              <input type="radio" id="star5" name="rating" value="5"  disabled="true"/><label for="star5" title="Rocks!">5 stars</label>
              <input type="radio" id="star4" name="rating" value="4"  checked disabled="true"/><label for="star4" title="Pretty good">4 stars</label>
              <input type="radio" id="star3" name="rating" value="3"  disabled="true" /><label for="star3" title="Meh">3 stars</label>
              <input type="radio" id="star2" name="rating" value="2"  disabled="true"/><label for="star2" title="Kinda bad">2 stars</label>
              <input type="radio" id="star1" name="rating" value="1"  disabled="true"/><label for="star1" title="Sucks big time">1 star</label>
            </span>
            <br>
            <b>Name: </b>{{enlist.uid.fname}}
          </td>
          <td style="width: 10%">{{enlist.car_model}}</td>
          <td style="width: 10%">${{enlist.fare}}</td>
          <td style="width: 10%">
            <form action="{% url 'book:bookdetails' request.session.userid %}" method="post">
              {% csrf_token %}
              <input type="hidden" name="eid" class="form-control" value={{enlist.id}}>
              <input type="submit" value="Book" class="btn" style="margin-left:0%;margin-top:4%">
            </form>
          </td>
        </tr>
        {% endfor %}
        {% elif error %}
        <tr><h3>{{error}}</h3></tr>



          </table>
      {% endif %}

      {% if some_enlists %}


      <table>
        <h4> Other Alternatives </h4>

        <tr>
          <th>Start Date</th>
          <th>Ride Offered By</th>
          <th>Car Model</th>
          <th>Fare Price</th>
          <th></th>
        </tr>
        {% for enlist in some_enlists %}

        <tr>

          <td style="width: 10%">{{enlist.start_date}} {{enlist.start_time}}</td>
          <td style="width: 30%;">
            <img src="{% static "images/img_avatar.png" %}" alt="John" style="width:30%; height: 25%">
            <span class="rating">
              <input type="radio" id="user_star5" name="rating" value="5"  disabled="true"/><label for="star5" title="Rocks!">5 stars</label>
              <input type="radio" id="user_star4" name="rating" value="4"  checked disabled="true"/><label for="star4" title="Pretty good">4 stars</label>
              <input type="radio" id="user_star3" name="rating" value="3"  disabled="true" /><label for="star3" title="Meh">3 stars</label>
              <input type="radio" id="user_star2" name="rating" value="2"  disabled="true"/><label for="star2" title="Kinda bad">2 stars</label>
              <input type="radio" id="user_star1" name="rating" value="1"  disabled="true"/><label for="star1" title="Sucks big time">1 star</label>
            </span>
            <br>
            <b>Name: </b>{{enlist.uid.fname}}
          </td>
          <td style="width: 10%">{{enlist.car_model}}</td>
          <td style="width: 10%">${{enlist.fare}}</td>
          <td style="width: 10%">
            <form action="{% url 'book:bookdetails' request.session.userid %}" method="post">
              {% csrf_token %}
              <input type="hidden" name="eid" class="form-control" value={{enlist.id}}>
              <input type="submit" value="Book" class="btn" style="margin-left:0%;margin-top:4%">
            </form>
          </td>
        </tr>
        {% endfor %}
        {% elif error %}
        <tr><h3>{{error}}</h3></tr>


      </table>
      {% endif %}
      {% if not all_enlists and not some_enlists %}
      <h3>Sorry, no matches found :(</h3>
      {% endif %}
    </div>
  </div>
</section>

<div class="container">
  <!-- Modal -->
  <div class="modal fade" id="myModal" role="dialog">
    <div class="modal-dialog">

      <!-- Modal content-->
      <div class="modal-content">
        <div class="modal-header">

          <h4 class="modal-title">Congrats</h4>
        </div>
        <div class="modal-body">
          <p>You successfully booked the Ride.</p>
        </div>
        <div class="modal-footer">
          <a href="{% url 'myride:upcoming' %}" id="btnYes" class="btn agree">Close</a>

        </div>
      </div>

    </div>
  </div>

</div>


<script src="{% static 'js/accordion.js' %}"></script>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>